# SD-Helper Configuration Sample
# Copy to ~/.sd-helper.yaml or place in project directory

# Default profile to use when --profile is not specified
default_profile: default

# Profile configurations
profiles:
  default:
    # IAM credentials
    username: <your-username>
    password: <your-password>
    domain_name: <your-domain>
    project_name: <your-project>       # e.g. cn-north-4_myproject
    iam_url: https://iam.cn-north-4.myhuaweicloud.com

    # LLM models configuration
    llm:
      default_model: qwen3-32b

      models:
        # ModelArts deployed model
        qwen3-32b:
          endpoint: https://<apig-endpoint>/v1/infers/<model-id>/v1/chat/completions
          type: modelarts
          temperature: 0.7
          max_tokens: 2048

        # Vision/multimodal model (vLLM)
        qwen3-vl-32b:
          endpoint: https://<apig-endpoint>/v1/infers/<model-id>/v1/chat/completions
          type: vl
          temperature: 0.7
          max_tokens: 2048

        # Pangu API
        pangu:
          endpoint: https://pangu.cn-north-4.myhuaweicloud.com/v1/chat/completions
          type: pangu
          temperature: 0.9
          max_tokens: 4096

        # Model with custom system prompt
        code-assistant:
          endpoint: https://<apig-endpoint>/v1/infers/<model-id>/v1/chat/completions
          type: modelarts
          temperature: 0.2
          max_tokens: 8192
          system: "You are a helpful coding assistant. Provide concise, correct code."

    # Docker image upload configuration
    docker:
      assets_file: 资产清单.txt        # 资产清单文件，只处理其中的 镜像 分区
      swr:
        endpoint: swr.cn-north-4.myhuaweicloud.com
        org: <your-swr-org>            # e.g. com-huaweicloud-dataengineering
      cleanup_after_push: false        # 设为 true 可在推送后删除本地镜像
