"""SD-Helper CLI: Service Delivery Engineer Tool for Huawei Cloud."""

from __future__ import annotations

from pathlib import Path

import click

from .commands import iam, llm, data, docker


SAMPLE_CONFIG = """\
# SD-Helper Configuration
# Generated by `sd-helper init`

# Default profile to use when --profile is not specified
default_profile: default

# Profile configurations
profiles:
  default:
    # IAM credentials
    username: <your-username>
    password: <your-password>
    domain_name: <your-domain>
    project_name: <your-project>       # e.g. cn-north-4_myproject
    iam_url: https://iam.cn-north-4.myhuaweicloud.com

    # LLM models configuration
    llm:
      default_model: qwen3-32b

      models:
        # ModelArts deployed model
        qwen3-32b:
          endpoint: https://<apig-endpoint>/v1/infers/<model-id>/v1/chat/completions
          type: modelarts
          temperature: 0.7
          max_tokens: 2048

        # Vision/multimodal model (vLLM)
        qwen3-vl-32b:
          endpoint: https://<apig-endpoint>/v1/infers/<model-id>/v1/chat/completions
          type: vl
          temperature: 0.7
          max_tokens: 2048

        # Pangu API
        pangu:
          endpoint: https://pangu.cn-north-4.myhuaweicloud.com/v1/chat/completions
          type: pangu
          temperature: 0.9
          max_tokens: 4096

    # Docker image upload configuration
    docker:
      assets_file: 资产清单.txt        # 资产清单文件，只处理其中的 镜像 分区
      swr:
        endpoint: swr.cn-north-4.myhuaweicloud.com
        org: <your-swr-org>            # e.g. com-huaweicloud-dataengineering
      cleanup_after_push: false        # 设为 true 可在推送后删除本地镜像
"""


@click.group()
@click.version_option(version="0.1.2")
def cli():
    """SD-Helper: CLI tool for Huawei Cloud Service Delivery Engineers."""
    pass


@cli.command()
@click.option("--local", is_flag=True, help="Write config to current directory instead of ~/.sd-helper.yaml")
@click.option("--force", is_flag=True, help="Overwrite existing config file")
def init(local, force):
    """Generate a sample config file to get started."""
    config_path = Path(".sd-helper.yaml") if local else Path.home() / ".sd-helper.yaml"

    if config_path.exists() and not force:
        click.echo(f"Config already exists: {config_path}")
        click.echo("Use --force to overwrite.")
        return

    config_path.write_text(SAMPLE_CONFIG)
    click.echo(f"Config written to: {config_path}")
    click.echo("Edit the file and fill in your credentials before use.")


cli.add_command(iam)
cli.add_command(llm)
cli.add_command(data)
cli.add_command(docker)


if __name__ == "__main__":
    cli()
